## Numerical Python End to End in Detail

### Numpy:

Numpy- is a **Numerical Python**

It is developed by **Travis Oliphant in 2005**

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays


### Why:

Numpy is built using **python,** and most of the part which requires fatser execution is **developed using c or c++**,So it is very fast in execution.

Numpy arrays are called as **ndarray**

Numpy has 50x speed as compared to python list, because NumPy is faster than lists because it uses **vectorized operations, optimized C code, memory efficiency, and cache efficiency**. These features allow NumPy to perform calculations on large amounts of data more quickly and efficiently than lists.

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it **stores numpy arrays at one continuous location** whereas lists are stored in scattered locations

Numpy codes are available at: https://github.com/numpy/numpy

### Installation of Numpy

In [1]:
import numpy as np

In [2]:
print("Numpy Version is:",np.__version__)

Numpy Version is: 1.24.3


In [13]:
# Create a numpy array using list

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

print('*'*100)

lst = [10,20,30,40]
ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
****************************************************************************************************
[10 20 30 40]
<class 'numpy.ndarray'>


In [14]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# lets check the dimentions of the array

print('Number of dimensions:',arr.ndim)


[1 2 3 4 5 6 7 8 9]
Number of dimensions: 1


In [15]:
# 2. Create numpy array using tuple

tup=(1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [18]:
# Different Dimentional Arrays:

In [2]:
# 1. 0-D array
import numpy as np
arr=np.array(9)
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

9
<class 'numpy.ndarray'>
Dimensons of array: 0


In [3]:
arr

array(9)

In [4]:
# 2. 1-D array

arr=np.array([1,2,3,4,45])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 1-D array
print('Element present at 4h index:',arr[4])

[ 1  2  3  4 45]
<class 'numpy.ndarray'>
Dimensons of array: 1
Element present at 4h index: 45


In [6]:
arr[::2] # step index

array([ 1,  3, 45])

In [7]:
arr[::-1]

array([45,  4,  3,  2,  1])

In [8]:
# 3. 2-D array
# Array having 1-D array as input element are called as 2-D array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print("Dimensons of array:",arr.ndim)

# Access elemnts an 2-D array
print('Element present at 1st index in axis 0:',arr[0,1]) # arr[0][1]

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimensons of array: 2
Element present at 1st index in axis 0: 2


In [9]:
import numpy as np
ar = [[1,2,3,4],[4,5,6,7],[4,5,6,7],[4,5,6,7]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2


In [10]:
# Access the elements of 2-D array

print(arr)
# dimensions
print("Dimensions: ",arr.ndim)
print('*'*100)

#one way is to write
print('arr[0][3] :',arr[0][3])
print('arr[0] :',arr[0])
print('arr[0][2] :',arr[0][2])

# another way is like
print('arr[1] :',arr[1])
print('arr[3,1] :',arr[3,1])

[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Dimensions:  2
****************************************************************************************************
arr[0][3] : 4
arr[0] : [1 2 3 4]
arr[0][2] : 3
arr[1] : [4 5 6 7]
arr[3,1] : 5


In [11]:
a=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(a,type(a), a.ndim)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]] <class 'numpy.ndarray'> 2


In [14]:
# reverse the elements from array
a[:,::-1]

array([[ 30,  20,  10],
       [ 60,  50,  40],
       [ 90,  80,  70],
       [120, 110, 100]])

In [13]:
# reverse the rows from array
a[::-1]

array([[100, 110, 120],
       [ 70,  80,  90],
       [ 40,  50,  60],
       [ 10,  20,  30]])

In [15]:
# reverse the rows and elements of array
a[::-1, ::-1]

array([[120, 110, 100],
       [ 90,  80,  70],
       [ 60,  50,  40],
       [ 30,  20,  10]])

In [30]:
# 4. 3-D Array
# array that has 2-D arrays (matrices) as its elemets is called 3D array

ar = [[[1,2,3], [4,5,6]], [[10,20,30], [40,50,60]]]
print(ar)
print(type(ar))
print('*'*100)

arr=np.array(ar)
print(arr)
print(type(arr))
print('*'*100)

print('Dimension of array :',arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
<class 'list'>
****************************************************************************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
Dimension of array : 3


In [33]:
# access the elements of the 3-D array

print(arr)
print(type(arr))
print('*'*100)

print('One way is:')
print('arr[1] :',arr[1])
print('arr[0][0] :',arr[0][0])
print('arr[0][0][2] :',arr[0][0][2])

print('*'*100)

# Another way
print('Another way is:')
print('arr[1] :',arr[1])
print('arr[0,0] :',arr[0,0])
print('arr[0,0,2] :',arr[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
****************************************************************************************************
One way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0][0] : [1 2 3]
arr[0][0][2] : 3
****************************************************************************************************
Another way is:
arr[1] : [[10 20 30]
 [40 50 60]]
arr[0,0] : [1 2 3]
arr[0,0,2] : 3


#### create an n dimensional array

lower dimention to higher dimention will possible by using **ndmin=..1/2/3/4/5/..**

but higher dimention to lower dimention will not possible by using ndmin function for we need to go with **array.reshape()** function

In [20]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [1]:
# lower to higher is possible but higher to lower not possible 
import numpy as np
arr1=np.array([[[[[1,2,3]]]]],ndmin=3)
arr1,arr1.ndim

(array([[[[[1, 2, 3]]]]]), 5)

In [16]:
arr2=np.array([1,2,3],ndmin=3)
arr,arr.ndim

(array([[[1, 2, 3, 4]]]), 3)

In [10]:
arr11 = np.array([1,2,3,4])
arr10 = arr11.reshape((1,1,1,1,4))
arr10.ndim

5

In [12]:
b=np.array([[[1,2,3], [4,5,6]], [[10,20,30], [40,50,60]]])
print(b,b.ndim)
b.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]] 3


(2, 2, 3)

In [27]:
b=np.array([[[1,2,3], [4,5,6]], [[10,20,30], [40,50,60]]])
b, b.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[10, 20, 30],
         [40, 50, 60]]]),
 3)

In [30]:
b[0,1,2]

6

### Array Slicing

In [32]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr,arr.ndim, arr.shape

(array([[[[[1, 2, 3, 4]]]]]), 5, (1, 1, 1, 1, 4))

In [21]:
# 5d array slicing
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])

1
2
3
4


In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Slice
print("Length: ",len(arr))
print(arr[5:9])

# [start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
Length:  9
[6 7 8 9]


In [40]:
print(arr[0:5])

[1 2 3 4 5]


###### Negative Indices

    Negative indices always start from last element of n-d 
    array i.e. -1st index is last element of ndarray.

In [41]:
print(arr)

[1 2 3 4 5 6 7 8 9]


[-9,-8,-7,-6,-5,-4,-3,-2,-1]

In [43]:
print(arr[-1])
print(arr[-5])
print(arr[-9])

9
5
1


In [47]:
print(arr[-9:-5])

[1 2 3 4]


In [48]:
# Step value in slicing a Numpy array
# here step is 2
print(arr)
print(arr[0:9:2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [49]:
print(arr[::2])  # ::2 >> 0 to 9 index by step index 2

print(arr[0:6:2]) # 0:6:2 >> 0 to 6 index by step value 2

[1 3 5 7 9]
[1 3 5]


###### Slicing of 2D Array

In [34]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('\n')
print(arr[1,2])

print(arr[1,1:4]) # arr

print(arr[0,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8
[7 8 9]
[2 3 4]


In [35]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
arr[0:,2:3]

array([[3],
       [8]])

In [37]:
arr[0:,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [36]:
arr[0,:3]

array([1, 2, 3])

In [60]:
print(arr[0:1,0:3]) # arr[location index from to,element index from to ]

[[1 2 3]]


In [61]:
print(arr[0:2,0:3]) # arr[location index from to, element index from to ]

[[1 2 3]
 [6 7 8]]


In [62]:
print(arr[0:2,2]) 

[3 8]


In [41]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size, arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15 (3, 5)


In [42]:
# 2, 3
# 20,30

print(arr[0:2,1:3]) 

print('\n')

# 20 30 40
# 22 33 44
print(arr[1:,1:4])

[[ 2  3]
 [20 30]]


[[20 30 40]
 [22 33 44]]


#### Slicing of 3D Array

In [46]:
arr=np.array([[[1,2,3],
               [5,6,7]],
              
              [[11,22,33],
               [55,66,77]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]
3


In [47]:
arr[0][1][1:3] # [array location , array row location, array coloumn location]

array([6, 7])

In [50]:
arr[1,1,0:2]

array([55, 66])

In [78]:
arr[1][1][1:3]

array([66, 77])

In [16]:
a=np.array([[[10,20,30],[40,50,60]],
            [[70,80,90],[100,110,120]],
            [[1,2,3],[4,5,6]],
            [[7,8,9],[11,22,33]]])
print(a,type(a), a.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 11  22  33]]] <class 'numpy.ndarray'> 3


In [17]:
a[:,:,2:]

array([[[ 30],
        [ 60]],

       [[ 90],
        [120]],

       [[  3],
        [  6]],

       [[  9],
        [ 33]]])

In [18]:
a[::-1] # reversed index

array([[[  7,   8,   9],
        [ 11,  22,  33]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[ 10,  20,  30],
        [ 40,  50,  60]]])

In [19]:
a[::-1,::-1]

array([[[ 11,  22,  33],
        [  7,   8,   9]],

       [[  4,   5,   6],
        [  1,   2,   3]],

       [[100, 110, 120],
        [ 70,  80,  90]],

       [[ 40,  50,  60],
        [ 10,  20,  30]]])

In [20]:
a[::-1,::-1,::-1]

array([[[ 33,  22,  11],
        [  9,   8,   7]],

       [[  6,   5,   4],
        [  3,   2,   1]],

       [[120, 110, 100],
        [ 90,  80,  70]],

       [[ 60,  50,  40],
        [ 30,  20,  10]]])

### Data Types in NumPy

list of all data types in NumPy:
    
        i/int - integer
        bool - boolean
        uint - unsigned integer
        f/float - float
        complex - complex float   
        string -string  
        M - datetime
        m - timedelta     
        O - object   
        U - unicode string
   

In [79]:
import numpy as np

In [80]:
# dtype

arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [81]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [25]:
# creating arrays with a defined data type

arr = np.array([1,2,3,4],dtype=str)
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [84]:
arr = np.array([1,2,3,4],dtype='i') # int
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [89]:
arr = np.array([1,2,3,4,5,6],dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [88]:
arr = np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float64


In [90]:
# int with 4 bytes

arr=np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

print('*'*100)

arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
****************************************************************************************************
[1 2 3 4]
int32


in python we are not responsible for memory management PVM is responsible for memory management

In [54]:
# Errors

# arr=np.array(['a','2','3'],dtype='i')
# print(arr) # ValueError: invalid literal for int() with base 10: 'a'

In [93]:
arr=np.array(['1','2','3'],dtype='i')
print(arr)

[1 2 3]


### Data Type Conversion

In [105]:
# float to int

arr = np.array([1.1, 2.2, 3.3, 4.4])
print('old array:',arr)
print('old array data type :',arr.dtype)
print('*'*100)
new_arr = arr.astype('i')
print('new array',new_arr)
print('new array data type :',new_arr.dtype)

old array: [1.1 2.2 3.3 4.4]
old array data type : float64
****************************************************************************************************
new array [1 2 3 4]
new array data type : int32


In [106]:
# int to bool

arr = np.array([1, 2, 3, 4, 0])
print('old array:',arr)
print('old array data type :',arr.dtype)
print('*'*100)
new_arr = arr.astype(bool)
print('new array',new_arr)
print('new array data type :',new_arr.dtype)

old array: [1 2 3 4 0]
old array data type : int32
****************************************************************************************************
new array [ True  True  True  True False]
new array data type : bool


### Difference Between Copy and View

copy : 

    A copy is a new array that has the same data as the original array. Changes made to the copy do not affect the original array, and vice versa
    
    
view :

    A view is a new array that refers to the same data as the original array. Changes made to the view affect the original array, and vice versa.

In [26]:
a=np.array([1,2,3,4,5])
print('original array :',a)
b=a.copy()
print('copied array :',b)
print('now we will update the original arrray "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)

original array : [1 2 3 4 5]
copied array : [1 2 3 4 5]
now we will update the original arrray "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original : [1 2 3 4 5]


In [27]:
a=np.array([1,2,3,4,5])
print('original array :',a)
b=a.view()
print('copied array :',b)
print('now we will update the original arrray "1 to 100"')
a[0]=100

print('original array after update :',a)
print('copied array after update in original :',b)

original array : [1 2 3 4 5]
copied array : [1 2 3 4 5]
now we will update the original arrray "1 to 100"
original array after update : [100   2   3   4   5]
copied array after update in original : [100   2   3   4   5]


In [107]:
# copy() : it is going to create new instance for your value

arr=np.array([1, 2, 3, 4, 5])
x = arr.copy() # seperate object required
arr[0]=42 # updated arr o th index

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [108]:
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
print(x)
x[0] = 100
print(x)

print(arr)
#print(x) 

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [112]:
# view() : 

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

# x = arr
x[0] = 200

print(arr)
print(x) 

[200   2   3   4   5]
[200   2   3   4   5]


In [113]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 4

print(a) # Output: [4 2 3]
print(b) # Output: [4 2 3]


[4 2 3]
[4 2 3]


###### base concept : how to identify copy or view

That will possible by using **"base"** funcion

If you are referring to identifying whether a NumPy array is a copy or a view (a different view of the same data), you can use the base attribute of the array. The base attribute returns None for arrays that own their data, and it returns the base object for arrays that are views

In [1]:
original_list = [1, 2, 3, 4, 5]

# Creating a Copy
copied_list = original_list.copy()  

# Creating a View
view_list = original_list

# Modifying the Copy and View
copied_list[0] = 10
view_list[1] = 20

print(original_list)  # Output: [1, 20, 3, 4, 5] (View modifies the original)
print(copied_list)    # Output: [10, 2, 3, 4, 5] (Copy doesn't modify the original)


[1, 20, 3, 4, 5]
[10, 2, 3, 4, 5]


In [2]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

# Creating a View
view_array = original_array.view()

# Creating a Copy
copied_array = original_array.copy()

print(view_array.base)   # Output: [1 2 3 4 5] (Original array is the base for the view)
print(copied_array.base) # Output: None (Copy has no base, it's an independent array)


[1 2 3 4 5]
None


### Numpy Array Reshaping

In [57]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(12,1)
print(newarr)

12
(12,)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [132]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)
print('\n')
newarr=arr.reshape(3,2,2)
print(newarr)

12
(12,)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [143]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr=arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [150]:
# create a 2D array and then convert it into 1D array

arr = np.array([[11,44,77,88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77 88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [151]:
arr = np.array([[11,44,77],[88,99,55]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[11 44 77]
 [88 99 55]]
2
****************************************************************************************************
[11 44 77 88 99 55]
1


In [152]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape(3,2)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[11 44]
 [77 88]
 [99 55]]
2


In [148]:
# convert 3D array into 1D array
arr = np.array([[[11,44,77,88,99,55]],[[111,441,717,188,919,515]]])
newarr = arr.reshape(12,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)


[[[ 11  44  77  88  99  55]]

 [[111 441 717 188 919 515]]]
3
****************************************************************************************************
[ 11  44  77  88  99  55 111 441 717 188 919 515]
1


In [154]:
arr = np.array([11,44,77,88,99,55,111,441,717,188,919,515])
newarr = arr.reshape(1,3,4)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[ 11  44  77  88  99  55 111 441 717 188 919 515]
1
****************************************************************************************************
[[[ 11  44  77  88]
  [ 99  55 111 441]
  [717 188 919 515]]]
3


In [149]:
# convert 4D array into 1D array

arr = np.array([[[[11,44,77,88,99,55]]]])
newarr = arr.reshape(6,)
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[[[[11 44 77 88 99 55]]]]
4
****************************************************************************************************
[11 44 77 88 99 55]
1


In [58]:
arr = np.array([11,44,77,88,99,55])
newarr = arr.reshape((3,2))
print(arr)
print(arr.ndim)
print('*'*100)
print(newarr)
print(newarr.ndim)

[11 44 77 88 99 55]
1
****************************************************************************************************
[[11 44]
 [77 88]
 [99 55]]
2


### Numpy Array Reshape Flatten unknown Dimensions

###### If user **dont know any one dimension out 3 dimensions** then numpy can obtain it for user. User have mension the **-1** for that dim.

In [62]:
# Unknown Dimension

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3, -1)

print(newarr) 

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


##### if u want to obtain a 1-D array using N-D array 

In [168]:
# Flattening(reshape/convert in scalar vector) an Array

arr=np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr.shape)

newarr=arr.reshape(-1)

print(newarr.shape)
print(newarr)

[[10 20 30]
 [40 50 60]]
(2, 3)
(6,)
[10 20 30 40 50 60]


### NumPy Array Iterating

Iterating: means that you going through each element of the array

In [169]:
arr =np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [171]:
# iterating on 2-D array 
arr = np.array([[11,22,33],[10,20,30]])

#print(arr)

for x in arr: # x is taking elemets here
    print(x)

[11 22 33]
[10 20 30]


In [174]:
# Iterating on scalar element of 2-D array

arr=np.array([[1, 2, 3],[4, 5, 6]])

for x in arr: # here x is holding list of elements
    for i in x:
        print(i)

1
2
3
4
5
6


In [181]:
# Iterating on scalar element of 3-D array

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
#     print(x,'\n')
    for i in x:
#          print(i,'\n')
         for j in i:
            print(j,'\n')

1 

2 

3 

4 

5 

6 

7 

8 

9 

10 

11 

12 



###### 1. Using nditer()

In [182]:
# Iterating on 3-D array
arr =np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

y = np.nditer(arr)

for x in y:
    print(x)

1
2
3
4
5
6
7
8


In [184]:
arr =np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [191]:
arr=np.array([[1,2,3,4],[88,88,3939,999]])

print(np.nditer(arr))

for i in np.nditer(arr):
    print(i)

1
2
3
4
88
88
3939
999


In [63]:
# Casting array element from one type to other data type

# Numpy can not at the movemet for that we need to go with "flags" para in nditer

arr=np.array([1, 2, 3])

for x in np.nditer(arr,flags=['buffered'],op_dtypes=['float']):
    print("int to float",x)
    
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['U']):
    print(x)
    
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

int to float 1.0
int to float 2.0
int to float 3.0
1
2
3
b'1'
b'2'
b'3'


In [65]:
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['complex']):
    print(i)

(1+0j)
(2+0j)
(3+0j)


In [252]:
# Slicing of an numpy array steps in iterations
# 2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[0:, 0:3:2]): # [Array location,index number::,step_size]
    print(x)

1
3
5
7


In [66]:
# 3D Array
# array[start:end:step, start:end:step, start:end:step]

arr=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])

for x in np.nditer(arr[1:,1::,1::3]):
    print(x)

55


In [29]:
arr=np.array([[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])

for i in np.nditer(arr[1:,1:,1:2]):
    print(i)

55


In [67]:
# create a 3D numpy array
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# slice the array along the first dimension
for i in np.nditer(array_3d[:,:,:]):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [303]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# slice the array with a step size of 2 along the first dimension
for i in np.nditer(array_3d[:,::,::2]):
    print(i)

1
3
4
6
7
9
10
12


###### 2. Using ndenumerate()

    Enumeration means mentioning sequence number of somethings one by one
    
    whenever we want to access any location of element in multi dimentional arrays that time we can use "ndenumerate"
    
    this method always return tuple of index and element

In [307]:
arr = np.array([1, 2, 3])

for x in np.ndenumerate(arr):
    print(x)
    
print('*'*100)    

for i,x in np.ndenumerate(arr):
    print("Index :",i,"Value",x)

((0,), 1)
((1,), 2)
((2,), 3)
****************************************************************************************************
Index : (0,) Value 1
Index : (1,) Value 2
Index : (2,) Value 3


In [310]:
# 2D array

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
for i, val in np.ndenumerate(arr):
    print("Index :",i,"Value",val)

[[1 2 3 4]
 [5 6 7 8]]
Index : (0, 0) Value 1
Index : (0, 1) Value 2
Index : (0, 2) Value 3
Index : (0, 3) Value 4
Index : (1, 0) Value 5
Index : (1, 1) Value 6
Index : (1, 2) Value 7
Index : (1, 3) Value 8


In [311]:
# 3D array

arr=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])

print(arr)
for i, val in np.ndenumerate(arr):
    print("Index :",i,"Value",val)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
Index : (0, 0, 0) Value 1
Index : (0, 0, 1) Value 2
Index : (0, 0, 2) Value 3
Index : (0, 0, 3) Value 4
Index : (0, 1, 0) Value 5
Index : (0, 1, 1) Value 6
Index : (0, 1, 2) Value 7
Index : (0, 1, 3) Value 8
Index : (1, 0, 0) Value 10
Index : (1, 0, 1) Value 20
Index : (1, 0, 2) Value 30
Index : (1, 0, 3) Value 40
Index : (1, 1, 0) Value 50
Index : (1, 1, 1) Value 60
Index : (1, 1, 2) Value 70
Index : (1, 1, 3) Value 80


### Joining Array

    While joining array we should remember "both arrays should have same dimentions"

###### 1. using concatenation 

        Combining two or more arrays along an existing axis. The resulting array has the same dimension as the original arrays.
        The dimension along which concatenation occurs remains the same. If you concatenate two 1D arrays, you get a longer 1D array. If you concatenate two 2D arrays along rows or columns, you get a larger 2D array.

In [312]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [313]:
# Array concatenation using axis option

# axis = 0 : it represents rows (default)
# axis = 1 : it represents columns

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,6 ], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # columnwise
print(arr)

print('*'*100)

arr = np.concatenate((arr1, arr2), axis=0) # rowwise
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
****************************************************************************************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


###### 2. using Stack Functions

         Stacking is same as concatenation, the only difference is that stacking is done along new axis.
         Joining two or more arrays along a new axis, thereby increasing the dimensionality of the arrays.
         The dimension along which stacking occurs becomes a new axis. For example, stacking two 1D arrays along a new axis creates a 2D array.

In [1]:
import numpy as np

arr1 = np.array([1, 2])  
arr2 = np.array([3, 4])

print(np.concatenate([arr1, arr2])) # [1 2 3 4]  
print(np.stack([arr1, arr2]))       # [[1 2]
                                    #  [3 4]]

[1 2 3 4]
[[1 2]
 [3 4]]


In [316]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

print('*'*100)

arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
****************************************************************************************************
[[1 2 3]
 [4 5 6]]


> ###### 2.1 using "hstack function()"

In [317]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


> ###### 2.2 using "vstack function()"

In [318]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


> ###### 2.3 using "dstack function()"

In [319]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


In [320]:
arr1 = np.array([[1, 2, 3],[11,22,33]])
arr2 = np.array([[4, 5, 6],[44,55,66]])

arr = np.dstack((arr1, arr2))
#  It stands for "depth-wise stack" and is used to stack arrays in sequence along the third axis (depth). 
# This is particularly useful when you have multiple 2D arrays and you want to combine them into a single 3D array.

print(arr) 

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[11 44]
  [22 55]
  [33 66]]]


### Splitting Array

    Joining merges multiple arrays into one and splitting breaks one array into multiple.
    
    syntax:
    
    np.array_split(array,no_split)
    np.split(array,no_split)

> ###### 1. using split()

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

newarr=np.split(arr,3)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
****************************************************************************************************
[1 2]
[3 4]
[5 6]


In [2]:
# using axis

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr)

newarr=np.split(arr,3,axis=1)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
****************************************************************************************************
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [4]:
# using axis

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

newarr=np.split(arr,2,axis=0)
print(newarr)

print('*'*100)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
****************************************************************************************************
[[1 2 3]]
[[4 5 6]]


In [337]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
#newarr = np.split(arr, 4) # This will raise an Value Error
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


> ###### 2. array_split()

    If no of elements are less than it adjust in last array 
    
    It does raise error this will adjust the element in array

In [339]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [342]:
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [343]:
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [346]:
newarr = np.array_split(arr,5)
print(newarr)

print('*'*100)

print(newarr[1])

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
****************************************************************************************************
[3]


In [349]:
# splitting on 2-D array

arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [76]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10],
              [11,12]])
newarr=np.array_split(arr,2,axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [363]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,4,axis=0)

for i in newarr:
    print(i,'\n')

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]] 

[[11 12]] 



In [364]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,2,axis=1)

for i in newarr:
    print(i,'\n')

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]] 

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]] 



In [369]:
# Array splitting on axis
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])

# print(arr)

newarr = np.array_split(arr, 3, axis=1)

print(newarr) 

print('*'*100)
print(arr,'\n')
newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
****************************************************************************************************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


> ###### 3. using hsplit() opposite of hstack()

In [382]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])

print(arr,'\n')
print('hstack() method:\n')
newarr = np.hstack(arr)
print(newarr,'\n')
newarr = np.hsplit(arr, 3)
# print(arr.shape)
print('hsplit() method:\n')
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

hstack() method:

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18] 

hsplit() method:

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

    The "where" method is used for searching the array

###### 1. where()

In [77]:
# finding element in 1-D array
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4) # element

print(arr)
print('Location of index:',x)

[1 2 3 4 5 4 4]
Location of index: (array([3, 5, 6], dtype=int64),)


In [8]:
# Arithmatic operation on numpy array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

print('\nAddition:',arr+1) # one element added in every element of array
print('\nSubtraction:',arr-1)
print('\nMultiplication:',arr*2)
print('\nDivision:',arr/2)

[[1 2 3]
 [4 5 6]]

Addition: [[2 3 4]
 [5 6 7]]

Subtraction: [[0 1 2]
 [3 4 5]]

Multiplication: [[ 2  4  6]
 [ 8 10 12]]

Division: [[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [5]:
# find the location of even number in my numpy array

arr=np.array([1,2,3,4,5,6,7,8])

x=np.where(arr%2==0)

print(arr)
print('Even number in array:',x)

[1 2 3 4 5 6 7 8]
Even number in array: (array([1, 3, 5, 7], dtype=int64),)


In [9]:
# find the location of odd number in numpy array

arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
loc=np.where(arr%2==1)

print('Odd number location:',loc)

Odd number location: (array([ 0,  2,  4,  6,  8, 10], dtype=int64),)


###### 2. searchsorted()

    perform a binary search in the array and returns the index where the specified value would be inserted to maintain the search order
    
    this method does not insert elements, it just return a location for element in the numpy array

In [20]:
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr, 7, side='left') # >>

print(arr)
print('location where element to be inserted',loc)

[5 7 8 9]
location where element to be inserted 1


In [21]:
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr, 7, side='right') # <<

print(arr)
print('location where element to be inserted',loc)

[5 7 8 9]
location where element to be inserted 2


In [2]:
import numpy as np
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr, 8.5, side='right') # <<

print(arr)
print('location where element to be inserted',loc)

[5 7 8 9]
location where element to be inserted 3


In [3]:
import numpy as np
arr=np.array([5,7,8,9])

loc=np.searchsorted(arr, 8.5, side='left') # >>

print(arr)
print('location where element to be inserted',loc)

[5 7 8 9]
location where element to be inserted 3


In [25]:
# multiple values

arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print('location where element to be inserted',x)

location where element to be inserted [1 2 3]


### Sorting Arrays

    Sorting means putting elements in an ordered sequence. like numeric or alphabetical, ascending or descending.

    sort(), that will sort a specified array.

In [26]:
# sort() on numerical arrays

arr=np.array([3,2,0,1])
res=np.sort(arr)
print('Input Array',arr)
print('Sorted Array',res)

Input Array [3 2 0 1]
Sorted Array [0 1 2 3]


In [28]:
# sort() on string array
arr = np.array(['banana', 'cherry', 'apple'])

res = np.sort(arr)

print('Input Array',arr)

print('Sorted Array',res)

Input Array ['banana' 'cherry' 'apple']
Sorted Array ['apple' 'banana' 'cherry']


In [29]:
# sort() boolean values
arr = np.array([True, False, True])

res = np.sort(arr)

print('Input Array',arr)

print('Sorted Array',res)

Input Array [ True False  True]
Sorted Array [False  True  True]


In [34]:
# sort() on 2D array

arr = np.array([[3, 2, 4], [5, 0, 1]])
res = np.sort(arr)

print('Input Array:\n',arr)
print('Sorted Array:\n',res)

Input Array:
 [[3 2 4]
 [5 0 1]]
Sorted Array:
 [[2 3 4]
 [0 1 5]]


In [5]:
# work on axis=0

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(arr)

# axis (axis=0), 
# which will result in a sorted 2D array where each column is sorted in ascending order.
res = np.sort(arr, axis=0)
print("Sorting on 0 axis:\n",res)

# axis (axis=1), 
# which will result in a sorted 2D array where each row is sorted in ascending order.
res = np.sort(arr, axis=1)
print("Sorting on 1 axis:\n",res)

[[3 2 4]
 [5 0 1]]
Sorting on 0 axis:
 [[3 0 1]
 [5 2 4]]
Sorting on 1 axis:
 [[2 3 4]
 [0 1 5]]


In [37]:
import numpy as np

# Create a 2D array
a = np.array([[3, 2, 4],
              [1, 5, 6],
              [9, 7, 8]])

# Sort the rows of the array along axis 1
sorted_array = np.sort(a, axis=1)
print('\n',sorted_array)
# Sort the columns of the array along axis 0
sorted_array = np.sort(a, axis=0)
print('\n',sorted_array)


 [[2 3 4]
 [1 5 6]
 [7 8 9]]

 [[1 2 4]
 [3 5 6]
 [9 7 8]]


### Filter Array

1. Getting some elements out of an existing array and creating a new array out of them is called filtering.
    
2. NumPy filter an array using a boolean index list.
    
3. A boolean index list is a list of booleans corresponding to indexes in the array.

In [41]:
arr=np.array([1,2,3,4,5])
x=[True, False, True, False, True]

newarr=arr[x]
print(newarr)

[1 3 5]


In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
# create an empty list
index=[]

# go through each element in arr
for element in arr:
    # if the element is higher than 4, set the value to True, otherwise false
    if element > 4:
        index.append(True)
    else:
        index.append(False)
        
print(index)
newarr=arr[index]
print(newarr)
    

[ 1  2  3  4  5  6  7  8  9 10]
[False, False, False, False, True, True, True, True, True, True]
[ 5  6  7  8  9 10]


In [47]:
# print a list of even number from original list using array filter

print(arr)

index = []

# i % 2 == 0

for i in arr:
    if i % 2 == 0:
        index.append(True)
    else:
        index.append(False)

print(index)

newarr = arr[index]

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [50]:
arr = np.array([11,223,45,677,8787,655,44,33,333,2,3,3,10])

filter_arr = arr > 100

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True  True  True False False  True False False False
 False]
[ 223  677 8787  655  333]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True False  True False]
[2 4 6]


### Other NumPy Functions

###### 1. arange()

In [53]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
arr=np.arange(5,25)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [81]:
arr=np.arange(5,51,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


###### 2. reshape()

        np.reshape(input,(shape))
        array.reshape(shape)

In [64]:
# 1D to 2D conversion
arr=np.arange(0,25)
print(arr)
# one way
arr_2d=np.reshape(arr,(5,5)) # or arr.reshape(5,5)
print('\n',arr_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
arr=np.arange(0,25)
print(arr)

# another way
arr_2d=arr.reshape(1,5,5)
print('\n',arr_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]


###### 3. min()

In [67]:
arr_2d.min()

0

###### 4. max()

the numpy.max() function is used to find the maximum value in the arr array

In [68]:
arr_2d.max()

24

###### 5. argmax()

The numpy.argmax() function is then used to find the index of the maximum value,

In [69]:
arr_2d.argmax()

24

###### 6. argsort()

In [70]:
arr_2d.argsort() # return indices of array

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]], dtype=int64)

###### 7. diagonal()

In [71]:
arr_2d.diagonal() # tirke elements

array([[0],
       [1],
       [2],
       [3],
       [4]])

###### 8. sum()

In [72]:
arr_2d.sum()

300

###### 9.mean()

In [73]:
arr_2d.mean()

12.0

###### 10. nonzero()

In [74]:
arr_2d.nonzero() # retrun index of non zero element

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4], dtype=int64))

###### 11. linspace()

In [6]:
arr=np.linspace(0,10,10)
print(arr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [7]:
arr=np.arange(0,25,10)
print(arr)

[ 0 10 20]


###### 12. ravel()

In [11]:
# flatten array
# used to multidimentional array to 1d array
print(arr_2d)
arr_2d.ravel()

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
# or

In [12]:
arr_2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

###### 13. random()

        random.rand
        random.randn
        random.randint
        random.random

In [82]:
ar = np.random.rand(3,3) # return 0 to 1 values as per given range
print(ar)

[[0.51087736 0.64675652 0.47679274]
 [0.53271422 0.67300866 0.60020765]
 [0.6389988  0.28724876 0.12863738]]


In [14]:
ar = np.random.randn(3,3) # return -1 to 1 values as per given range
print(ar)

[[ 1.25859564 -1.18789922  0.75394951]
 [ 0.45112185  0.77902537  2.14655498]
 [ 0.30351417 -1.2621043   0.04417183]]


In [95]:
ar = np.random.randint(10,20) # return integer values as per given range
print(ar)

13


In [96]:
ar = np.random.random(10) # return random values as per given range
print(ar)

[0.71840663 0.02120173 0.28153639 0.83888184 0.49722656 0.93357414
 0.74888821 0.37593208 0.36271191 0.32065715]


###### 14. eye()

In [15]:
# unit matrix or identity matrix
ar = np.eye(3,3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ar = np.eye(5,5,2)
print(ar)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###### 15. ones()

In [18]:
ar = np.ones((2,3))
print(ar)

[[1. 1. 1.]
 [1. 1. 1.]]


###### 16. zeros()

In [19]:
ar = np.zeros((2,3))
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]]


###### 17. diag()

In [20]:
ar = np.diag((2,10,2))
print(ar)

[[ 2  0  0]
 [ 0 10  0]
 [ 0  0  2]]


In [21]:
ar = np.diag((1,2,3,4))
print(ar)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


###### 18. dot()

In [22]:
# Matrix multiplication / Dot product

ar1 = np.arange(1,5)
ar2 = np.arange(1,5)

print(ar1)
print(ar2)

ar_1 = ar1.reshape(2,2)
ar_2 = ar2.reshape(2,2)

print(ar_1)
print(ar_2)

[1 2 3 4]
[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [23]:
ar_1.dot(ar_2)

array([[ 7, 10],
       [15, 22]])

In [105]:
print(ar_1)

ar_1*2


[[1 2]
 [3 4]]


array([[2, 4],
       [6, 8]])