In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30,40, 50]
array = np.array(list1)
print(array, type(array))
print(array.ndim)

[10 20 30 40 50] <class 'numpy.ndarray'>
1


In [3]:
array.size

5

In [4]:
array.dtype

dtype('int32')

In [5]:
array.itemsize

4

In [6]:
array.data

In [8]:
array = np.arange(25).reshape(5,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
digonal = array.diagonal(offset=0)
digonal

array([ 0,  6, 12, 18, 24])

In [25]:
digonal = [array[i][i] for i in range(len(array))]
digonal

[0, 6, 12, 18, 24]

In [27]:
s_array = array * array
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [31]:
array = np.array([np.arange(6).reshape(2,3),np.arange(6).reshape(2,3)])
array

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [37]:
array = np.array([[1,0,3],[10,20,30]], dtype='bool')
array

array([[ True, False,  True],
       [ True,  True,  True]])

In [45]:
array = np.zeros((3,2,3),dtype='float')
array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
emp = np.empty((2,2))
emp

array([[2.12199579e-314, 1.35595531e-311],
       [6.16593926e-321, 1.35595531e-311]])

In [54]:
array = np.arange(0,2, 0.2).reshape(5,2)
array

array([[0. , 0.2],
       [0.4, 0.6],
       [0.8, 1. ],
       [1.2, 1.4],
       [1.6, 1.8]])

In [60]:
array = np.linspace(1,10,10)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.full((3,3,3),10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [62]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [75]:
array = np.asarray(s_array,order='F')
array 

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [81]:
array * 5

array([[   0,    5,   20,   45,   80],
       [ 125,  180,  245,  320,  405],
       [ 500,  605,  720,  845,  980],
       [1125, 1280, 1445, 1620, 1805],
       [2000, 2205, 2420, 2645, 2880]])

In [82]:
array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [97]:
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.logspace(1,10,num=10, base=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [104]:
list1 = list(range(1,10))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
np.fromiter(list1, dtype='float', count=-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
def generator():
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype='float', count=-1 )
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [118]:
np.asarray(array, dtype='float')

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]])

In [122]:
np.fromiter(list1, dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [131]:
np.eye(5,5,0,dtype='str')

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [135]:
np.full((4,5),999111)

array([[999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111]])

In [136]:
array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [137]:
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [139]:
array.shape

(5, 5)

In [141]:
array.reshape((1,25))

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
        169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576]])

In [142]:
np.reshape(array, (5,5))

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [143]:
np.shape(array)

(5, 5)

In [146]:
array = np.array([1,2,3], ndmin=3)
array

array([[[1, 2, 3]]])

In [147]:
array = np.array([[[[[1,2,3]]]]], ndmin=3)
array

array([[[[[1, 2, 3]]]]])

In [148]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [156]:
arr[::-1,  ::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [150]:
arr[:,-1]

array([ 5, 10])

In [151]:
np.diagonal(arr,3)

array([ 4, 10])

In [157]:
arr=np.array([[[1,2,3],
               [5,6,7]],
              
              [[11,22,33],
               [55,66,77]]])
print(arr)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]


In [165]:
arr = [np.diagonal(i,0) for i in arr]
arr

[array([1, 6]), array([11, 66])]

In [166]:
arr

[array([1, 6]), array([11, 66])]

In [167]:
arr=np.array([[[1,2,3],
               [5,6,7]],
              
              [[11,22,33],
               [55,66,77]]])

In [168]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [174]:
result = arr[[0, 1], [0, 1], 2]
print(result)


[ 3 77]


In [183]:
arr[[0,1], [0,0]]

array([[ 1,  2,  3],
       [11, 22, 33]])

In [184]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [198]:
arr[[0,1], [0,1], [0,2]]

array([ 1, 77])

In [199]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [200]:
arr[[0,1], [0,1], [1,0]]

array([ 2, 55])

In [202]:
arr[0:, 0:, 1:2]

array([[[ 2],
        [ 6]],

       [[22],
        [66]]])

In [203]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [213]:
arr[[0,1,1], [0,0,1], [0,2,2]]

array([ 1, 33, 77])

In [214]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [216]:
arr[[0,0,1,1,0,0], [0,1,0,1,0,1], [0,0,1,1,2,2]]

array([ 1,  5, 22, 66,  3,  7])

In [217]:
arr=np.array([[1,2,3],
               [5,6,7],
              [11,22,33],
               [55,66,77]])
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [220]:
arr[[0,1,2,3,0,1],[0,0,1,1,2,2]]

array([ 1,  5, 22, 66,  3,  7])

In [221]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [225]:
arr.astype(int)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [226]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [231]:
c = arr.copy()
v = arr.view()

In [232]:
c[0,0]=11

In [233]:
c

array([[11,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [234]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [235]:
v[0,0]=111

In [236]:
v

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [237]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [240]:
c.base

In [241]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [247]:
arr.size, arr.shape

(12, (4, 3))

In [244]:
x = arr.reshape((1,2,6))

In [245]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [249]:
x.reshape(12)

array([111,   2,   3,   5,   6,   7,  11,  22,  33,  55,  66,  77])

In [251]:
for i in x:
    print(i)

[[111   2   3   5   6   7]
 [ 11  22  33  55  66  77]]


In [252]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [255]:
for i in arr:
    for j in i:
        print(j)

111
2
3
5
6
7
11
22
33
55
66
77


In [256]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [257]:
for i in x:
    for j in i:
        for k in j:
            print(k)


111
2
3
5
6
7
11
22
33
55
66
77


In [258]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [259]:
y = np.nditer(x)
y

In [260]:
print(y)

In [261]:
for i in y:
    print(i)

111
2
3
5
6
7
11
22
33
55
66
77


In [262]:
for i in np.nditer(arr):
    print(i)

111
2
3
5
6
7
11
22
33
55
66
77


In [267]:
for i in np.nditer(arr):
      print(i)
    
    
for j in np.ndenumerate(arr):
      print(j)

111
2
3
5
6
7
11
22
33
55
66
77
((0, 0), 111)
((0, 1), 2)
((0, 2), 3)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((2, 0), 11)
((2, 1), 22)
((2, 2), 33)
((3, 0), 55)
((3, 1), 66)
((3, 2), 77)


In [275]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])
print(a)
print(b)


[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [276]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1])

In [279]:
c =  a.reshape((3,2))
d =  b.reshape((3,2))
print(c)
print()
print(d)

[[1 2]
 [3 4]
 [5 6]]

[[6 5]
 [4 3]
 [2 1]]


In [282]:
np.concatenate((c,d), axis=1)

array([[1, 2, 6, 5],
       [3, 4, 4, 3],
       [5, 6, 2, 1]])

In [283]:
a, b

(array([1, 2, 3, 4, 5, 6]), array([6, 5, 4, 3, 2, 1]))

In [285]:
np.stack((a,b), axis=0)

array([[1, 2, 3, 4, 5, 6],
       [6, 5, 4, 3, 2, 1]])

In [287]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [290]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [292]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [295]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [298]:
np.array_split(arr,10)

[array([[111,   2,   3]]),
 array([[5, 6, 7]]),
 array([[11, 22, 33]]),
 array([[55, 66, 77]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [306]:
np.split(arr,2)

[array([[111,   2,   3],
        [  5,   6,   7]]),
 array([[11, 22, 33],
        [55, 66, 77]])]

In [307]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [311]:
np.sort(arr, axis=0)

array([[  5,   2,   3],
       [ 11,   6,   7],
       [ 55,  22,  33],
       [111,  66,  77]])

In [313]:
np.sort(arr, axis=1)

array([[  2,   3, 111],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [2]:
import numpy as np

arr=np.array([[8,6,3],
               [9,6,7],
              [4,5,7],
               [8,7,4]])
arr

array([[8, 6, 3],
       [9, 6, 7],
       [4, 5, 7],
       [8, 7, 4]])

In [5]:
np.split(arr, 4)

[array([[8, 6, 3]]),
 array([[9, 6, 7]]),
 array([[4, 5, 7]]),
 array([[8, 7, 4]])]

In [10]:
np.array_split(arr, 8)

[array([[8, 6, 3]]),
 array([[9, 6, 7]]),
 array([[4, 5, 7]]),
 array([[8, 7, 4]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [27]:
arr

array([[8, 6, 3],
       [9, 6, 7],
       [4, 5, 7],
       [8, 7, 4]])

In [37]:
np.where(arr % 2 == 0, 'Even', 'odd')

array([['Even', 'Even', 'odd'],
       ['odd', 'Even', 'odd'],
       ['Even', 'odd', 'odd'],
       ['Even', 'odd', 'Even']], dtype='<U4')

In [38]:
arr

array([[8, 6, 3],
       [9, 6, 7],
       [4, 5, 7],
       [8, 7, 4]])

In [39]:
arr.sort()

In [40]:
arr

array([[3, 6, 8],
       [6, 7, 9],
       [4, 5, 7],
       [4, 7, 8]])

In [49]:
arr = np.array([9,4,7,6,3,2,9,1])
arr = np.sort(arr)
print(arr)
np.searchsorted(arr, [5,10,15])

[1 2 3 4 6 7 9 9]


array([4, 8, 8], dtype=int64)

In [50]:
arr

array([1, 2, 3, 4, 6, 7, 9, 9])

In [51]:
arr=np.array([[8,6,3],
               [9,6,7],
              [4,5,7],
               [8,7,4]])
arr

array([[8, 6, 3],
       [9, 6, 7],
       [4, 5, 7],
       [8, 7, 4]])

In [53]:
np.sort(arr, axis=1)

array([[3, 6, 8],
       [6, 7, 9],
       [4, 5, 7],
       [4, 7, 8]])

In [52]:
np.sort(arr, axis=0)

array([[4, 5, 3],
       [8, 6, 4],
       [8, 6, 7],
       [9, 7, 7]])

In [80]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [58]:
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [65]:
np.power(a,b)

array([  1,  32, 729])

In [66]:
np.reciprocal(a,b)

array([1, 0, 0])

In [74]:
np.conjugate(b)

array([1, 0, 0])

In [76]:
a-b

array([0, 2, 3])

In [84]:
np.amax(b)

6

In [81]:
b

array([4, 5, 6])

In [88]:
np.amin(b, axis=0)

4

In [89]:
np.average(a)

2.0

In [92]:
(4+5+6)/3

5.0

In [93]:
(1+2+3)/3

2.0

In [97]:
np.sum(a)

6

In [102]:
a= np.array([1,2,3,4,5,6,7,8])
print(a)
x = [True ,False, True, False, True, False, True, False ]
b = a[x]
b

[1 2 3 4 5 6 7 8]


array([1, 3, 5, 7])

In [103]:
np.mean(a)

4.5

In [105]:
np.median(a)

4.5

In [106]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

index = []

for i in arr:
    if i < 5:
        index.append(True)
    else:
        index.append(False)

print(index)

b = arr[index]
print(b)    

[ 1  2  3  4  5  6  7  8  9 10]
[True, True, True, True, False, False, False, False, False, False]
[1 2 3 4]


In [107]:
import random

In [134]:
np.random.rand(2,3,3)

array([[[0.27005029, 0.3725756 , 0.54196561],
        [0.77345688, 0.33437675, 0.96156449],
        [0.07615652, 0.35848803, 0.5245825 ]],

       [[0.31569149, 0.25382123, 0.17119279],
        [0.23704103, 0.02597252, 0.75007031],
        [0.3827546 , 0.94081505, 0.65663378]]])

In [128]:
np.random.random((3,3))

array([[0.11180091, 0.99777687, 0.26105496],
       [0.22343308, 0.53840673, 0.77418829],
       [0.68874651, 0.93166473, 0.24965741]])

In [137]:
np.random.randint(1,12,10)

array([ 2,  9,  2,  7, 10,  6,  6,  3,  8,  5])

In [139]:
np.random.ranf((3,3))

array([[0.73340297, 0.32308103, 0.70795923],
       [0.47621383, 0.24138588, 0.54418155],
       [0.41079042, 0.99992526, 0.3568877 ]])

In [143]:
np.random.randn(10)

array([ 1.2343951 ,  1.07474451,  0.02912807, -1.26017484, -1.17888068,
        1.04319455, -0.00320979, -0.029374  ,  0.56919026, -0.84264881])