In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30,40, 50]
array = np.array(list1)
print(array, type(array))
print(array.ndim)

[10 20 30 40 50] <class 'numpy.ndarray'>
1


In [3]:
array.size

5

In [4]:
array.dtype

dtype('int32')

In [5]:
array.itemsize

4

In [6]:
array.data

In [8]:
array = np.arange(25).reshape(5,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
digonal = array.diagonal(offset=0)
digonal

array([ 0,  6, 12, 18, 24])

In [25]:
digonal = [array[i][i] for i in range(len(array))]
digonal

[0, 6, 12, 18, 24]

In [27]:
s_array = array * array
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [31]:
array = np.array([np.arange(6).reshape(2,3),np.arange(6).reshape(2,3)])
array

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [37]:
array = np.array([[1,0,3],[10,20,30]], dtype='bool')
array

array([[ True, False,  True],
       [ True,  True,  True]])

In [45]:
array = np.zeros((3,2,3),dtype='float')
array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
emp = np.empty((2,2))
emp

array([[2.12199579e-314, 1.35595531e-311],
       [6.16593926e-321, 1.35595531e-311]])

In [54]:
array = np.arange(0,2, 0.2).reshape(5,2)
array

array([[0. , 0.2],
       [0.4, 0.6],
       [0.8, 1. ],
       [1.2, 1.4],
       [1.6, 1.8]])

In [60]:
array = np.linspace(1,10,10)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.full((3,3,3),10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [62]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [75]:
array = np.asarray(s_array,order='F')
array 

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [81]:
array * 5

array([[   0,    5,   20,   45,   80],
       [ 125,  180,  245,  320,  405],
       [ 500,  605,  720,  845,  980],
       [1125, 1280, 1445, 1620, 1805],
       [2000, 2205, 2420, 2645, 2880]])

In [82]:
array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [97]:
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.logspace(1,10,num=10, base=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [104]:
list1 = list(range(1,10))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
np.fromiter(list1, dtype='float', count=-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
def generator():
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype='float', count=-1 )
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [118]:
np.asarray(array, dtype='float')

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]])

In [122]:
np.fromiter(list1, dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [131]:
np.eye(5,5,0,dtype='str')

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [135]:
np.full((4,5),999111)

array([[999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111],
       [999111, 999111, 999111, 999111, 999111]])

In [136]:
array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [137]:
s_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [139]:
array.shape

(5, 5)

In [141]:
array.reshape((1,25))

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
        169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576]])

In [142]:
np.reshape(array, (5,5))

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [143]:
np.shape(array)

(5, 5)

In [146]:
array = np.array([1,2,3], ndmin=3)
array

array([[[1, 2, 3]]])

In [147]:
array = np.array([[[[[1,2,3]]]]], ndmin=3)
array

array([[[[[1, 2, 3]]]]])

In [148]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [156]:
arr[::-1,  ::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [150]:
arr[:,-1]

array([ 5, 10])

In [151]:
np.diagonal(arr,3)

array([ 4, 10])

In [157]:
arr=np.array([[[1,2,3],
               [5,6,7]],
              
              [[11,22,33],
               [55,66,77]]])
print(arr)

[[[ 1  2  3]
  [ 5  6  7]]

 [[11 22 33]
  [55 66 77]]]


In [165]:
arr = [np.diagonal(i,0) for i in arr]
arr

[array([1, 6]), array([11, 66])]

In [166]:
arr

[array([1, 6]), array([11, 66])]

In [167]:
arr=np.array([[[1,2,3],
               [5,6,7]],
              
              [[11,22,33],
               [55,66,77]]])

In [168]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [174]:
result = arr[[0, 1], [0, 1], 2]
print(result)


[ 3 77]


In [183]:
arr[[0,1], [0,0]]

array([[ 1,  2,  3],
       [11, 22, 33]])

In [184]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [198]:
arr[[0,1], [0,1], [0,2]]

array([ 1, 77])

In [199]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [200]:
arr[[0,1], [0,1], [1,0]]

array([ 2, 55])

In [202]:
arr[0:, 0:, 1:2]

array([[[ 2],
        [ 6]],

       [[22],
        [66]]])

In [203]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [213]:
arr[[0,1,1], [0,0,1], [0,2,2]]

array([ 1, 33, 77])

In [214]:
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 22, 33],
        [55, 66, 77]]])

In [216]:
arr[[0,0,1,1,0,0], [0,1,0,1,0,1], [0,0,1,1,2,2]]

array([ 1,  5, 22, 66,  3,  7])

In [217]:
arr=np.array([[1,2,3],
               [5,6,7],
              [11,22,33],
               [55,66,77]])
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [220]:
arr[[0,1,2,3,0,1],[0,0,1,1,2,2]]

array([ 1,  5, 22, 66,  3,  7])

In [221]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [225]:
arr.astype(int)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [226]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [231]:
c = arr.copy()
v = arr.view()

In [232]:
c[0,0]=11

In [233]:
c

array([[11,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [234]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 22, 33],
       [55, 66, 77]])

In [235]:
v[0,0]=111

In [236]:
v

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [237]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [240]:
c.base

In [241]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [247]:
arr.size, arr.shape

(12, (4, 3))

In [244]:
x = arr.reshape((1,2,6))

In [245]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [249]:
x.reshape(12)

array([111,   2,   3,   5,   6,   7,  11,  22,  33,  55,  66,  77])

In [251]:
for i in x:
    print(i)

[[111   2   3   5   6   7]
 [ 11  22  33  55  66  77]]


In [252]:
arr

array([[111,   2,   3],
       [  5,   6,   7],
       [ 11,  22,  33],
       [ 55,  66,  77]])

In [255]:
for i in arr:
    for j in i:
        print(j)

111
2
3
5
6
7
11
22
33
55
66
77


In [256]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [257]:
for i in x:
    for j in i:
        for k in j:
            print(k)


111
2
3
5
6
7
11
22
33
55
66
77


In [258]:
x

array([[[111,   2,   3,   5,   6,   7],
        [ 11,  22,  33,  55,  66,  77]]])

In [259]:
y = np.nditer(x)
y

In [260]:
print(y)

In [261]:
for i in y:
    print(i)

111
2
3
5
6
7
11
22
33
55
66
77


In [262]:
for i in np.nditer(arr):
    print(i)

111
2
3
5
6
7
11
22
33
55
66
77


In [267]:
for i in np.nditer(arr):
      print(i)
    
    
for j in np.ndenumerate(arr):
      print(j)

111
2
3
5
6
7
11
22
33
55
66
77
((0, 0), 111)
((0, 1), 2)
((0, 2), 3)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((2, 0), 11)
((2, 1), 22)
((2, 2), 33)
((3, 0), 55)
((3, 1), 66)
((3, 2), 77)


In [275]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])
print(a)
print(b)


[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [276]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1])

In [279]:
c =  a.reshape((3,2))
d =  b.reshape((3,2))
print(c)
print()
print(d)

[[1 2]
 [3 4]
 [5 6]]

[[6 5]
 [4 3]
 [2 1]]


In [282]:
np.concatenate((c,d), axis=1)

array([[1, 2, 6, 5],
       [3, 4, 4, 3],
       [5, 6, 2, 1]])